services:
  - type: web
    name: yt-audio-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -w 1 -k gevent -b 0.0.0.0:$PORT --timeout 120"
     envVars:
      - key: COOKIES_BASE64
        sync: false
